using System;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace Transkript;

/// <summary>
/// Manages the system-tray icon using WinForms NotifyIcon.
/// Loads app.ico from the application directory (generated by generate_icon.ps1).
/// </summary>
public sealed class TrayManager : IDisposable
{
    private readonly NotifyIcon _notify;

    public event Action? ExitRequested;
    public event Action? SettingsRequested;

    public TrayManager()
    {
        var menu = new ContextMenuStrip();

        var header = menu.Items.Add("Transkript");
        header.Enabled = false;
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("Paramètres", null, (_, _) => SettingsRequested?.Invoke());
        menu.Items.Add(new ToolStripSeparator());
        menu.Items.Add("Quitter", null, (_, _) => ExitRequested?.Invoke());

        _notify = new NotifyIcon
        {
            Text    = "Transkript — chargement…",
            Icon    = LoadIcon(),
            Visible = true,
            ContextMenuStrip = menu,
        };
    }

    public void SetStatus(string status)
    {
        string text = $"Transkript — {status}";
        _notify.Text = text.Length > 127 ? text[..127] : text;
    }

    public void ShowBalloon(string title, string message)
        => _notify.ShowBalloonTip(3000, title, message, ToolTipIcon.Info);

    private static Icon LoadIcon()
    {
        string icoPath = Path.Combine(AppContext.BaseDirectory, "app.ico");
        if (File.Exists(icoPath))
            return new Icon(icoPath, 32, 32);

        // Fallback si app.ico absent
        using var bmp = new Bitmap(32, 32);
        using var g   = Graphics.FromImage(bmp);
        g.Clear(Color.FromArgb(255, 28, 28, 30));
        g.FillEllipse(new SolidBrush(Color.FromArgb(255, 255, 59, 48)), 10, 10, 12, 12);
        return Icon.FromHandle(bmp.GetHicon());
    }

    public void Dispose()
    {
        _notify.Visible = false;
        _notify.Dispose();
    }
}
